os: linux
dist: xenial
language: python
python: 3.8.5

jobs:
  include:
    - name: Python 3.9
      python: 3.9.0
      env: TOXENV=py39

    - name: Python 3.8
      env: TOXENV=py38

    - name: Coverage
      env: TOXENV=coverage

    - name: Code style checks
      env: TOXENV=style

    - name: Bandit security audit
      env: TOXENV=bandit

    - name: Build documentation and check warnings
      env: TOXENV=build-docs
      addons:
        apt:
          packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

    - name: macOS
      env:
        - TOXENV=py38
        - PATH=/usr/local/opt/python@3.8/bin:$PATH
      os: osx
      osx_image: xcode12
      language: shell
      addons:
        homebrew:
          packages:
            - python@3.8
      install:
        - pip3 install tox

    - name: jwst
      env: TOXENV=jwst

    - name: romancal
      env: TOXENV=romancal

  allow_failures:
    - name: jwst
      env: TOXENV=jwst

    - name: romancal
      env: TOXENV=romancal

install:
  - pip install tox

script:
  - tox
